# Changes here will be overwritten by Copier
_commit: v0.4.0
_src_path: https://github.com/jjjermiah/PyPackageBuilder
author_email: johndoe@example.com
author_full_name: John Doe
build_backend: hatch
git_init: true
github_username: jjjermiah
package_description: 'TODO:: Add a short description of just_another_python_package
    here.'
package_name: just_another_python_package
pixi_install: true
pixi_install_envs:
- dev
project_name: Just Another Python Package
project_slug: just-another-python-package
python_version: '3.10'
software_license: MIT License
